services:
  mongo:
    image: mongo
    hostname: "mongo"
    container_name: 'mongo_methodology'
    volumes:
      - ./.docker/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
      - ./data/user-progress:/data/db
    environment:
      MONGO_INITDB_DATABASE: "grupo13db"
      MONGO_INITDB_ROOT_USERNAME: "local"
      MONGO_INITDB_ROOT_PASSWORD: "secret"
    ports:
      - "27017:27017"